uploads = []
outputs = []

[[generated]]
id = "b_dBXu1xYuoZN06qOXchO"
uri = "file://artifacts/flower-world/public/images/gallery-1.png"
type = "image"
title = "Macro shot of exotic purple orchid"

[[generated]]
id = "QRDs-AGmGhEcteL3PBRdi"
uri = "file://artifacts/flower-world/public/images/gallery-2.png"
type = "image"
title = "Field of wild prairie roses"

[[generated]]
id = "QyZ3HCwght5kVADNTLaet"
uri = "file://artifacts/flower-world/public/images/gallery-3.png"
type = "image"
title = "Elegant white lotus flower"

[[generated]]
id = "YOY4Q48BaJ7WvSobvJl_q"
uri = "file://artifacts/flower-world/public/images/gallery-4.png"
type = "image"
title = "Vibrant red flame lily"

[[generated]]
id = "_1cD8AYs6iW3qHbgZOfbW"
uri = "file://artifacts/flower-world/public/images/gallery-5.png"
type = "image"
title = "Blue poppy in himalayan landscape"

[[generated]]
id = "ebkbbbF_gJg-vdbGvOb0w"
uri = "file://artifacts/flower-world/public/images/gallery-6.png"
type = "image"
title = "King protea majestic close up"

[[generated]]
id = "MAwDe8nAhbIW8prsr3rQv"
uri = "file://artifacts/flower-world/public/images/hero-bg.png"
type = "image"
title = "Hero background dark floral"

[[generated]]
id = "BXlUSzNy8AVshTlRWtrXl"
uri = "file://attached_assets/generated_images/breathtaking_macro_photograph_of_2d8f.png"
type = "image"
title = "generated_image"

[[generated]]
id = "98dMqeJ2R6jyhadAmii1v"
uri = "file://attached_assets/generated_images/elegant_japanese_cherry_blossom_1180.png"
type = "image"
title = "generated_image"

[[generated]]
id = "IYxjiP6wy_FTapi93zLSy"
uri = "file://artifacts/flower-world/public/images/gallery-7.png"
type = "image"
title = "generated_image"

[[generated]]
id = "31jLBBcemjlgRi2Ph1dN0"
uri = "file://artifacts/flower-world/public/images/gallery-9.png"
type = "image"
title = "generated_image"

[[generated]]
id = "A9zTBm6UnO87CSJlhMJpv"
uri = "file://artifacts/flower-world/public/images/gallery-8.png"
type = "image"
title = "generated_image"
